/**
 * 英語slug → 日本語名 の静的マッピング
 * PokeAPIのfetchを減らすためのキャッシュ
 */
import { findBestJaMatch, normalizeJaText } from "./japanese-match";

export const EN_TO_JA: Record<string, string> = {
  // Gen 1
  bulbasaur: "フシギダネ", ivysaur: "フシギソウ", venusaur: "フシギバナ",
  charmander: "ヒトカゲ", charmeleon: "リザード", charizard: "リザードン",
  squirtle: "ゼニガメ", wartortle: "カメール", blastoise: "カメックス",
  caterpie: "キャタピー", metapod: "トランセル", butterfree: "バタフリー",
  weedle: "ビードル", kakuna: "コクーン", beedrill: "スピアー",
  pidgey: "ポッポ", pidgeotto: "ピジョン", pidgeot: "ピジョット",
  rattata: "コラッタ", raticate: "ラッタ",
  spearow: "オニスズメ", fearow: "オニドリル",
  ekans: "アーボ", arbok: "アーボック",
  pikachu: "ピカチュウ", raichu: "ライチュウ",
  sandshrew: "サンド", sandslash: "サンドパン",
  "nidoran-f": "ニドラン♀", nidorina: "ニドリーナ", nidoqueen: "ニドクイン",
  "nidoran-m": "ニドラン♂", nidorino: "ニドリーノ", nidoking: "ニドキング",
  clefairy: "ピッピ", clefable: "ピクシー",
  vulpix: "ロコン", ninetales: "キュウコン",
  jigglypuff: "プリン", wigglytuff: "プクリン",
  zubat: "ズバット", golbat: "ゴルバット",
  oddish: "ナゾノクサ", gloom: "クサイハナ", vileplume: "ラフレシア",
  paras: "パラス", parasect: "パラセクト",
  venonat: "コンパン", venomoth: "モルフォン",
  diglett: "ディグダ", dugtrio: "ダグトリオ",
  meowth: "ニャース", persian: "ペルシアン",
  psyduck: "コダック", golduck: "ゴルダック",
  mankey: "マンキー", primeape: "オコリザル",
  growlithe: "ガーディ", arcanine: "ウインディ",
  poliwag: "ニョロモ", poliwhirl: "ニョロゾ", poliwrath: "ニョロボン",
  abra: "ケーシィ", kadabra: "ユンゲラー", alakazam: "フーディン",
  machop: "ワンリキー", machoke: "ゴーリキー", machamp: "カイリキー",
  bellsprout: "マダツボミ", weepinbell: "ウツドン", victreebel: "ウツボット",
  tentacool: "メノクラゲ", tentacruel: "ドククラゲ",
  geodude: "イシツブテ", graveler: "ゴローン", golem: "ゴローニャ",
  ponyta: "ポニータ", rapidash: "ギャロップ",
  slowpoke: "ヤドン", slowbro: "ヤドラン",
  magnemite: "コイル", magneton: "レアコイル",
  farfetchd: "カモネギ",
  doduo: "ドードー", dodrio: "ドードリオ",
  seel: "パウワウ", dewgong: "ジュゴン",
  grimer: "ベトベター", muk: "ベトベトン",
  shellder: "シェルダー", cloyster: "パルシェン",
  gastly: "ゴース", haunter: "ゴースト", gengar: "ゲンガー",
  onix: "イワーク",
  drowzee: "スリープ", hypno: "スリーパー",
  krabby: "クラブ", kingler: "キングラー",
  voltorb: "ビリリダマ", electrode: "マルマイン",
  exeggcute: "タマタマ", exeggutor: "ナッシー",
  cubone: "カラカラ", marowak: "ガラガラ",
  hitmonlee: "サワムラー", hitmonchan: "エビワラー",
  lickitung: "ベロリンガ",
  koffing: "ドガース", weezing: "マタドガス",
  rhyhorn: "サイホーン", rhydon: "サイドン",
  chansey: "ラッキー",
  tangela: "モンジャラ",
  kangaskhan: "ガルーラ",
  horsea: "タッツー", seadra: "シードラ",
  goldeen: "トサキント", seaking: "アズマオウ",
  staryu: "ヒトデマン", starmie: "スターミー",
  "mr-mime": "バリヤード",
  scyther: "ストライク",
  jynx: "ルージュラ",
  electabuzz: "エレブー",
  magmar: "ブーバー",
  pinsir: "カイロス",
  tauros: "ケンタロス",
  magikarp: "コイキング", gyarados: "ギャラドス",
  lapras: "ラプラス",
  ditto: "メタモン",
  eevee: "イーブイ", vaporeon: "シャワーズ", jolteon: "サンダース",
  flareon: "ブースター",
  porygon: "ポリゴン",
  omanyte: "オムナイト", omastar: "オムスター",
  kabuto: "カブト", kabutops: "カブトプス",
  aerodactyl: "プテラ",
  snorlax: "カビゴン",
  articuno: "フリーザー", zapdos: "サンダー", moltres: "ファイヤー",
  dratini: "ミニリュウ", dragonair: "ハクリュー", dragonite: "カイリュー",
  mewtwo: "ミュウツー", mew: "ミュウ",

  // Gen 2
  chikorita: "チコリータ", bayleef: "ベイリーフ", meganium: "メガニウム",
  cyndaquil: "ヒノアラシ", quilava: "マグマラシ", typhlosion: "バクフーン",
  totodile: "ワニノコ", croconaw: "アリゲイツ", feraligatr: "オーダイル",
  sentret: "オタチ", furret: "オオタチ",
  hoothoot: "ホーホー", noctowl: "ヨルノズク",
  ledyba: "レディバ", ledian: "レディアン",
  spinarak: "イトマル", ariados: "アリアドス",
  crobat: "クロバット",
  chinchou: "チョンチー", lanturn: "ランターン",
  pichu: "ピチュー",
  cleffa: "ピィ",
  igglybuff: "ププリン",
  togepi: "トゲピー", togetic: "トゲチック",
  natu: "ネイティ", xatu: "ネイティオ",
  mareep: "メリープ", flaaffy: "モコモコ", ampharos: "デンリュウ",
  bellossom: "キレイハナ",
  marill: "マリル", azumarill: "マリルリ",
  sudowoodo: "ウソッキー",
  politoed: "ニョロトノ",
  hoppip: "ハネッコ", skiploom: "ポポッコ", jumpluff: "ワタッコ",
  aipom: "エイパム",
  sunkern: "ヒマナッツ", sunflora: "キマワリ",
  yanma: "ヤンヤンマ",
  wooper: "ウパー", quagsire: "ヌオー",
  espeon: "エーフィ", umbreon: "ブラッキー",
  murkrow: "ヤミカラス",
  slowking: "ヤドキング", "slowking-galar": "ガラルヤドキング",
  misdreavus: "ムウマ",
  unown: "アンノーン",
  wobbuffet: "ソーナンス",
  girafarig: "キリンリキ",
  pineco: "クヌギダマ", forretress: "フォレトス",
  dunsparce: "ノコッチ",
  gligar: "グライガー",
  steelix: "ハガネール",
  snubbull: "ブルー", granbull: "グランブル",
  qwilfish: "ハリーセン",
  scizor: "ハッサム",
  shuckle: "ツボツボ",
  heracross: "ヘラクロス",
  sneasel: "ニューラ",
  teddiursa: "ヒメグマ", ursaring: "リングマ",
  slugma: "マグマッグ", magcargo: "マグカルゴ",
  swinub: "ウリムー", piloswine: "イノムー",
  corsola: "サニーゴ",
  remoraid: "テッポウオ", octillery: "オクタン",
  delibird: "デリバード",
  mantine: "マンタイン",
  skarmory: "エアームド",
  houndour: "デルビル", houndoom: "ヘルガー",
  kingdra: "キングドラ",
  phanpy: "ゴマゾウ", donphan: "ドンファン",
  porygon2: "ポリゴン２",
  stantler: "オドシシ",
  smeargle: "ドーブル",
  tyrogue: "バルキー",
  hitmontop: "カポエラー",
  smoochum: "ムチュール",
  elekid: "エレキッド",
  magby: "ブビィ",
  miltank: "ミルタンク",
  blissey: "ハピナス",
  raikou: "ライコウ", entei: "エンテイ", suicune: "スイクン",
  larvitar: "ヨーギラス", pupitar: "サナギラス", tyranitar: "バンギラス",
  lugia: "ルギア", "ho-oh": "ホウオウ",
  celebi: "セレビィ",

  // Gen 3
  treecko: "キモリ", grovyle: "ジュプトル", sceptile: "ジュカイン",
  torchic: "アチャモ", combusken: "ワカシャモ", blaziken: "バシャーモ",
  mudkip: "ミズゴロウ", marshtomp: "ヌマクロー", swampert: "ラグラージ",
  poochyena: "ポチエナ", mightyena: "グラエナ",
  zigzagoon: "ジグザグマ", linoone: "マッスグマ",
  wurmple: "ケムッソ", silcoon: "カラサリス", beautifly: "アゲハント",
  cascoon: "マユルド", dustox: "ドクケイル",
  lotad: "ハスボー", lombre: "ハスブレロ", ludicolo: "ルンパッパ",
  seedot: "タネボー", nuzleaf: "コノハナ", shiftry: "ダーテング",
  taillow: "スバメ", swellow: "オオスバメ",
  wingull: "キャモメ", pelipper: "ペリッパー",
  ralts: "ラルトス", kirlia: "キルリア", gardevoir: "サーナイト",
  surskit: "アメタマ", masquerain: "アメモース",
  shroomish: "キノココ", breloom: "キノガッサ",
  slakoth: "ナマケロ", vigoroth: "ヤルキモノ", slaking: "ケッキング",
  nincada: "ツチニン", ninjask: "テッカニン", shedinja: "ヌケニン",
  whismur: "ゴニョニョ", loudred: "ドゴーム", exploud: "バクオング",
  makuhita: "マクノシタ", hariyama: "ハリテヤマ",
  azurill: "ルリリ",
  nosepass: "ノズパス",
  skitty: "エネコ", delcatty: "エネコロロ",
  sableye: "ヤミラミ",
  mawile: "クチート",
  aron: "ココドラ", lairon: "コドラ", aggron: "ボスゴドラ",
  meditite: "アサナン", medicham: "チャーレム",
  electrike: "ラクライ", manectric: "ライボルト",
  plusle: "プラスル", minun: "マイナン",
  volbeat: "バルビート", illumise: "イルミーゼ",
  roselia: "ロゼリア",
  gulpin: "ゴクリン", swalot: "マルノーム",
  carvanha: "キバニア", sharpedo: "サメハダー",
  wailmer: "ホエルコ", wailord: "ホエルオー",
  numel: "ドンメル", camerupt: "バクーダ",
  torkoal: "コータス",
  spoink: "バネブー", grumpig: "ブーピッグ",
  spinda: "パッチール",
  trapinch: "ナックラー", vibrava: "ビブラーバ", flygon: "フライゴン",
  cacnea: "サボネア", cacturne: "ノクタス",
  swablu: "チルット", altaria: "チルタリス",
  zangoose: "ザングース",
  seviper: "ハブネーク",
  lunatone: "ルナトーン", solrock: "ソルロック",
  barboach: "ドジョッチ", whiscash: "ナマズン",
  corphish: "ヘイガニ", crawdaunt: "シザリガー",
  baltoy: "ヤジロン", claydol: "ネンドール",
  lileep: "リリーラ", cradily: "ユレイドル",
  anorith: "アノプス", armaldo: "アーマルド",
  feebas: "ヒンバス", milotic: "ミロカロス",
  castform: "ポワルン",
  kecleon: "カクレオン",
  shuppet: "カゲボウズ", banette: "ジュペッタ",
  duskull: "ヨマワル", dusclops: "サマヨール",
  tropius: "トロピウス",
  chimecho: "チリーン",
  absol: "アブソル",
  wynaut: "ソーナノ",
  snorunt: "ユキワラシ", glalie: "オニゴーリ",
  spheal: "タマザラシ", sealeo: "トドグラー", walrein: "トドゼルガ",
  clamperl: "パールル", huntail: "ハンテール", gorebyss: "サクラビス",
  relicanth: "ジーランス",
  luvdisc: "ラブカス",
  bagon: "タツベイ", shelgon: "コモルー", salamence: "ボーマンダ",
  beldum: "ダンバル", metang: "メタング", metagross: "メタグロス",
  regirock: "レジロック", regice: "レジアイス", registeel: "レジスチル",
  latias: "ラティアス", latios: "ラティオス",
  kyogre: "カイオーガ", groudon: "グラードン", rayquaza: "レックウザ",
  jirachi: "ジラーチ", deoxys: "デオキシス",

  // Gen 4
  turtwig: "ナエトル", grotle: "ハヤシガメ", torterra: "ドダイトス",
  chimchar: "ヒコザル", monferno: "モウカザル", infernape: "ゴウカザル",
  piplup: "ポッチャマ", prinplup: "ポッタイシ", empoleon: "エンペルト",
  starly: "ムックル", staravia: "ムクバード", staraptor: "ムクホーク",
  bidoof: "ビッパ", bibarel: "ビーダル",
  kricketot: "コロボーシ", kricketune: "コロトック",
  shinx: "コリンク", luxio: "ルクシオ", luxray: "レントラー",
  budew: "スボミー", roserade: "ロズレイド",
  cranidos: "ズガイドス", rampardos: "ラムパルド",
  shieldon: "タテトプス", bastiodon: "トリデプス",
  burmy: "ミノムッチ", wormadam: "ミノマダム", mothim: "ガーメイル",
  combee: "ミツハニー", vespiquen: "ビークイン",
  pachirisu: "パチリス",
  buizel: "ブイゼル", floatzel: "フローゼル",
  cherubi: "チェリンボ", cherrim: "チェリム",
  shellos: "カラナクシ", gastrodon: "トリトドン",
  ambipom: "エテボース",
  drifloon: "フワンテ", drifblim: "フワライド",
  buneary: "ミミロル", lopunny: "ミミロップ",
  mismagius: "ムウマージ",
  honchkrow: "ドンカラス",
  glameow: "ニャルマー", purugly: "ブニャット",
  chingling: "リーシャン",
  stunky: "スカンプー", skuntank: "スカタンク",
  bronzor: "ドーミラー", bronzong: "ドータクン",
  bonsly: "ウソハチ",
  "mime-jr": "マネネ",
  happiny: "ピンプク",
  chatot: "ペラップ",
  spiritomb: "ミカルゲ",
  gible: "フカマル", gabite: "ガバイト", garchomp: "ガブリアス",
  munchlax: "ゴンベ",
  riolu: "リオル", lucario: "ルカリオ",
  hippopotas: "ヒポポタス", hippowdon: "カバルドン",
  skorupi: "スコルピ", drapion: "ドラピオン",
  croagunk: "グレッグル", toxicroak: "ドクロッグ",
  carnivine: "マスキッパ",
  finneon: "ケイコウオ", lumineon: "ネオラント",
  mantyke: "タマンタ",
  snover: "ユキカブリ", abomasnow: "ユキノオー",
  weavile: "マニューラ",
  magnezone: "ジバコイル",
  lickilicky: "ベロベルト",
  rhyperior: "ドサイドン",
  tangrowth: "モジャンボ",
  electivire: "エレキブル",
  magmortar: "ブーバーン",
  togekiss: "トゲキッス",
  yanmega: "メガヤンマ",
  leafeon: "リーフィア", glaceon: "グレイシア",
  gliscor: "グライオン",
  mamoswine: "マンムー",
  "porygon-z": "ポリゴンＺ",
  gallade: "エルレイド",
  probopass: "ダイノーズ",
  dusknoir: "ヨノワール",
  froslass: "ユキメノコ",
  rotom: "ロトム",
  "rotom-heat": "ヒートロトム", "rotom-wash": "ウォッシュロトム", "rotom-frost": "フロストロトム", "rotom-fan": "スピンロトム", "rotom-mow": "カットロトム",
  uxie: "ユクシー", mesprit: "エムリット", azelf: "アグノム",
  dialga: "ディアルガ", palkia: "パルキア",
  heatran: "ヒードラン",
  regigigas: "レジギガス",
  giratina: "ギラティナ",
  cresselia: "クレセリア",
  phione: "フィオネ", manaphy: "マナフィ",
  darkrai: "ダークライ",
  shaymin: "シェイミ",
  arceus: "アルセウス",

  // Gen 5
  victini: "ビクティニ",
  snivy: "ツタージャ", servine: "ジャノビー", serperior: "ジャローダ",
  tepig: "ポカブ", pignite: "チャオブー", emboar: "エンブオー",
  oshawott: "ミジュマル", dewott: "フタチマル", samurott: "ダイケンキ",
  patrat: "ミネズミ", watchog: "ミルホッグ",
  lillipup: "ヨーテリー", herdier: "ハーデリア", stoutland: "ムーランド",
  purrloin: "チョロネコ", liepard: "レパルダス",
  pansage: "ヤナップ", simisage: "ヤナッキー",
  pansear: "バオップ", simisear: "バオッキー",
  panpour: "ヒヤップ", simipour: "ヒヤッキー",
  munna: "ムンナ", musharna: "ムシャーナ",
  pidove: "マメパト", tranquill: "ハトーボー", unfezant: "ケンホロウ",
  blitzle: "シママ", zebstrika: "ゼブライカ",
  roggenrola: "ダンゴロ", boldore: "ガントル", gigalith: "ギガイアス",
  woobat: "コロモリ", swoobat: "ココロモリ",
  drilbur: "モグリュー", excadrill: "ドリュウズ",
  audino: "タブンネ",
  timburr: "ドッコラー", gurdurr: "ドテッコツ", conkeldurr: "ローブシン",
  tympole: "オタマロ", palpitoad: "ガマガル", seismitoad: "ガマゲロゲ",
  throh: "ナゲキ", sawk: "ダゲキ",
  sewaddle: "クルミル", swadloon: "クルマユ", leavanny: "ハハコモリ",
  venipede: "フシデ", whirlipede: "ホイーガ", scolipede: "ペンドラー",
  cottonee: "モンメン", whimsicott: "エルフーン",
  petilil: "チュリネ", lilligant: "ドレディア",
  "basculin-red-striped": "バスラオ",
  sandile: "メグロコ", krokorok: "ワルビル", krookodile: "ワルビアル",
  darumaka: "ダルマッカ", darmanitan: "ヒヒダルマ",
  maractus: "マラカッチ",
  dwebble: "イシズマイ", crustle: "イワパレス",
  scraggy: "ズルッグ", scrafty: "ズルズキン",
  sigilyph: "シンボラー",
  yamask: "デスマス", cofagrigus: "デスカーン",
  tirtouga: "プロトーガ", carracosta: "アバゴーラ",
  archen: "アーケン", archeops: "アーケオス",
  trubbish: "ヤブクロン", garbodor: "ダストダス",
  zorua: "ゾロア", zoroark: "ゾロアーク",
  minccino: "チラーミィ", cinccino: "チラチーノ",
  gothita: "ゴチム", gothorita: "ゴチミル", gothitelle: "ゴチルゼル",
  solosis: "ユニラン", duosion: "ダブラン", reuniclus: "ランクルス",
  ducklett: "コアルヒー", swanna: "スワンナ",
  vanillite: "バニプッチ", vanillish: "バニリッチ", vanilluxe: "バイバニラ",
  deerling: "シキジカ", sawsbuck: "メブキジカ",
  emolga: "エモンガ",
  karrablast: "カブルモ", escavalier: "シュバルゴ",
  foongus: "タマゲタケ", amoonguss: "モロバレル",
  frillish: "プルリル", jellicent: "ブルンゲル",
  alomomola: "ママンボウ",
  joltik: "バチュル", galvantula: "デンチュラ",
  ferroseed: "テッシード", ferrothorn: "ナットレイ",
  klink: "ギアル", klang: "ギギアル", klinklang: "ギギギアル",
  tynamo: "シビシラス", eelektrik: "シビビール", eelektross: "シビルドン",
  elgyem: "リグレー", beheeyem: "オーベム",
  litwick: "ヒトモシ", lampent: "ランプラー", chandelure: "シャンデラ",
  axew: "キバゴ", fraxure: "オノンド", haxorus: "オノノクス",
  cubchoo: "クマシュン", beartic: "ツンベアー",
  cryogonal: "フリージオ",
  shelmet: "チョボマキ", accelgor: "アギルダー",
  stunfisk: "マッギョ",
  mienfoo: "コジョフー", mienshao: "コジョンド",
  druddigon: "クリムガン",
  golett: "ゴビット", golurk: "ゴルーグ",
  pawniard: "コマタナ", bisharp: "キリキザン",
  bouffalant: "バッフロン",
  rufflet: "ワシボン", braviary: "ウォーグル",
  vullaby: "バルチャイ", mandibuzz: "バルジーナ",
  heatmor: "クイタラン",
  durant: "アイアント",
  deino: "モノズ", zweilous: "ジヘッド", hydreigon: "サザンドラ",
  larvesta: "メラルバ", volcarona: "ウルガモス",
  cobalion: "コバルオン", terrakion: "テラキオン", virizion: "ビリジオン",
  tornadus: "トルネロス", thundurus: "ボルトロス", landorus: "ランドロス",
  reshiram: "レシラム", zekrom: "ゼクロム", kyurem: "キュレム",
  keldeo: "ケルディオ", meloetta: "メロエッタ", genesect: "ゲノセクト",

  // Gen 6
  chespin: "ハリマロン", quilladin: "ハリボーグ", chesnaught: "ブリガロン",
  fennekin: "フォッコ", braixen: "テールナー", delphox: "マフォクシー",
  froakie: "ケロマツ", frogadier: "ゲコガシラ", greninja: "ゲッコウガ",
  bunnelby: "ホルビー", diggersby: "ホルード",
  fletchling: "ヤヤコマ", fletchinder: "ヒノヤコマ", talonflame: "ファイアロー",
  scatterbug: "コフキムシ", spewpa: "コフーライ", vivillon: "ビビヨン",
  litleo: "シシコ", pyroar: "カエンジシ",
  flabebe: "フラベベ", floette: "フラエッテ", florges: "フラージェス",
  skiddo: "メェークル", gogoat: "ゴーゴート",
  pancham: "ヤンチャム", pangoro: "ゴロンダ",
  furfrou: "トリミアン",
  espurr: "ニャスパー", meowstic: "ニャオニクス",
  honedge: "ヒトツキ", doublade: "ニダンギル", aegislash: "ギルガルド",
  spritzee: "シュシュプ", aromatisse: "フレフワン",
  swirlix: "ペロッパフ", slurpuff: "ペロリーム",
  inkay: "マーイーカ", malamar: "カラマネロ",
  binacle: "カメテテ", barbaracle: "ガメノデス",
  skrelp: "クズモー", dragalge: "ドラミドロ",
  clauncher: "ウデッポウ", clawitzer: "ブロスター",
  helioptile: "エリキテル", heliolisk: "エレザード",
  tyrunt: "チゴラス", tyrantrum: "ガチゴラス",
  amaura: "アマルス", aurorus: "アマルルガ",
  sylveon: "ニンフィア",
  hawlucha: "ルチャブル",
  dedenne: "デデンネ",
  carbink: "メレシー",
  goomy: "ヌメラ", sliggoo: "ヌメイル", goodra: "ヌメルゴン",
  klefki: "クレッフィ",
  phantump: "ボクレー", trevenant: "オーロット",
  pumpkaboo: "バケッチャ", gourgeist: "パンプジン",
  bergmite: "カチコール", avalugg: "クレベース",
  noibat: "オンバット", noivern: "オンバーン",
  xerneas: "ゼルネアス", yveltal: "イベルタル", zygarde: "ジガルデ",
  diancie: "ディアンシー", hoopa: "フーパ", volcanion: "ボルケニオン",

  // Gen 7
  rowlet: "モクロー", dartrix: "フクスロー", decidueye: "ジュナイパー",
  litten: "ニャビー", torracat: "ニャヒート", incineroar: "ガオガエン",
  popplio: "アシマリ", brionne: "オシャマリ", primarina: "アシレーヌ",
  pikipek: "ツツケラ", trumbeak: "ケララッパ", toucannon: "ドデカバシ",
  yungoos: "ヤングース", gumshoos: "デカグース",
  grubbin: "アゴジムシ", charjabug: "デンヂムシ", vikavolt: "クワガノン",
  crabrawler: "マケンカニ", crabominable: "ケケンカニ",
  oricorio: "オドリドリ",
  cutiefly: "アブリー", ribombee: "アブリボン",
  rockruff: "イワンコ", lycanroc: "ルガルガン",
  wishiwashi: "ヨワシ",
  mareanie: "ヒドイデ", toxapex: "ドヒドイデ",
  mudbray: "ドロバンコ", mudsdale: "バンバドロ",
  dewpider: "シズクモ", araquanid: "オニシズクモ",
  fomantis: "カリキリ", lurantis: "ラランテス",
  morelull: "ネマシュ", shiinotic: "マシェード",
  salandit: "ヤトウモリ", salazzle: "エンニュート",
  stufful: "ヌイコグマ", bewear: "キテルグマ",
  bounsweet: "アマカジ", steenee: "アママイコ", tsareena: "アマージョ",
  comfey: "キュワワー",
  oranguru: "ヤレユータン",
  passimian: "ナゲツケサル",
  wimpod: "ウツロイド", golisopod: "グソクムシャ",
  sandygast: "スナバァ", palossand: "シロデスナ",
  pyukumuku: "ナマコブシ",
  "type-null": "タイプ：ヌル", silvally: "シルヴァディ",
  minior: "メテノ",
  komala: "ネッコアラ",
  turtonator: "バクガメス",
  togedemaru: "トゲデマル",
  mimikyu: "ミミッキュ",
  bruxish: "ハギギシリ",
  drampa: "ジジーロン",
  dhelmise: "ダダリン",
  "jangmo-o": "ジャラコ", "hakamo-o": "ジャランゴ", "kommo-o": "ジャラランガ",
  "tapu-koko": "カプ・コケコ", "tapu-lele": "カプ・テテフ",
  "tapu-bulu": "カプ・ブルル", "tapu-fini": "カプ・レヒレ",
  cosmog: "コスモッグ", cosmoem: "コスモウム",
  solgaleo: "ソルガレオ", lunala: "ルナアーラ",
  nihilego: "ニヒルゴ", buzzwole: "マッシブーン",
  pheromosa: "フェローチェ", xurkitree: "デンジュモク",
  celesteela: "テッカグヤ", kartana: "カミツルギ",
  guzzlord: "アクジキング",
  necrozma: "ネクロズマ",
  magearna: "マギアナ", marshadow: "マーシャドー",
  poipole: "ベベノム", naganadel: "アーゴヨン",
  stakataka: "ツンデツンデ", blacephalon: "ズガドーン",
  zeraora: "ゼラオラ",
  meltan: "メルタン", melmetal: "メルメタル",

  // Gen 8
  grookey: "サルノリ", thwackey: "バチンキー", rillaboom: "ゴリランダー",
  scorbunny: "ヒバニー", raboot: "ラビフット", cinderace: "エースバーン",
  sobble: "メッソン", drizzile: "ジメレオン", inteleon: "インテレオン",
  skwovet: "リス", greedent: "ヨクバリス",
  rookidee: "ツブツブ", corvisquire: "アオガラス", corviknight: "アーマーガア",
  blipbug: "サッチムシ", dottler: "レドームシ", orbeetle: "イオルブ",
  nickit: "クスネ", thievul: "フォクスライ",
  gossifleur: "ヒメンカ", eldegoss: "ワタシラガ",
  wooloo: "ウールー", dubwool: "バイウールー",
  chewtle: "カムカメ", drednaw: "カジリガメ",
  yamper: "ワンパチ", boltund: "パルスワン",
  rolycoly: "タンドン", carkol: "トロッゴン", coalossal: "セキタンザン",
  applin: "カジッチュ", flapple: "アップリュー", appletun: "タルップル",
  silicobra: "サダイジャ", sandaconda: "サダイジャ",
  cramorant: "ウッウ",
  arrokuda: "サシカマス", barraskewda: "カマスジョー",
  toxel: "エレズン", toxtricity: "ストリンダー",
  sizzlipede: "ヤクデ", centiskorch: "マルヤクデ",
  clobbopus: "タタッコ", grapploct: "オトスパス",
  sinistea: "ヤバチャ", polteageist: "ポットデス",
  hatenna: "ミブリム", hattrem: "テブリム", hatterene: "ブリムオン",
  impidimp: "イカサマン", morgrem: "ギモー", grimmsnarl: "オーロンゲ",
  obstagoon: "タチフサグマ",
  perrserker: "ニャイキング",
  cursola: "サニゴーン",
  sirfetchd: "ネギガナイト",
  "mr-rime": "バリコオル",
  runerigus: "ガラルマタドガス",
  milcery: "マホミル", alcremie: "マホイップ",
  falinks: "タイレーツ",
  pincurchin: "バチンウニ",
  snom: "ユキハミ", frosmoth: "モスノウ",
  stonjourner: "イシヘンジン",
  eiscue: "コオリッポ",
  indeedee: "イエッサン",
  morpeko: "モルペコ",
  cufant: "ゾウドウ", copperajah: "ダイオウドウ",
  dracozolt: "パッチラゴン", arctozolt: "パッチルドン",
  dracovish: "ウオチルドン", arctovish: "ウオノラゴン",
  duraludon: "ジュラルドン",
  dreepy: "ドラメシヤ", drakloak: "ドロンチ", dragapult: "ドラパルト",
  zacian: "ザシアン", zamazenta: "ザマゼンタ",
  eternatus: "ムゲンダイナ",
  kubfu: "ダクマ", urshifu: "ウーラオス",
  zarude: "ザルード",
  regieleki: "レジエレキ", regidrago: "レジドラゴ",
  glastrier: "ブリザポス", spectrier: "レイスポス",
  calyrex: "バドレックス",
  wyrdeer: "アヤシシ",
  kleavor: "バサギリ",
  ursaluna: "ガチグマ",
  basculegion: "イダイトウ",
  sneasler: "ニューラ（ヒスイ）",
  overqwil: "ハリーマン",
  enamorus: "ラブトロス",

  // Gen 9
  sprigatito: "ニャオハ", floragato: "ニャローテ", meowscarada: "マスカーニャ",
  fuecoco: "ホゲータ", crocalor: "アチゲータ", skeledirge: "ラウドボーン",
  quaxly: "クワッス", quaxwell: "ウェルカモ", quaquaval: "ウェーニバル",
  lechonk: "グルトン", oinkologne: "パフュートン",
  tarountula: "クモノ", spidops: "クモノイド",
  nymble: "バッタリン", lokix: "エクスレッグ",
  pawmi: "パモ", pawmo: "パモット", pawmot: "パーモット",
  tandemaus: "ワッカネズミ", maushold: "イッカネズミ",
  fidough: "パピモッチ", dachsbun: "バウッツェル",
  smoliv: "ミニーブ", dolliv: "オリーヴォ", arboliva: "オリーヴァ",
  squawkabilly: "イキリンコ",
  nacli: "コジオ", naclstack: "シオカリオン", garganacl: "キョジオーン",
  charcadet: "カルボウ", armarouge: "グレンアルマ", ceruledge: "ソウブレイズ",
  tadbulb: "タツナミ", bellibolt: "ハラバリー",
  wattrel: "カイデン", kilowattrel: "ジュミラフ",
  maschiff: "オラチフ", mabosstiff: "マフィティフ",
  shroodle: "シルシュルー", grafaiai: "タギングル",
  bramblin: "サボラン", brambleghast: "タタリメコ",
  toedscool: "ノノクラゲ", toedscruel: "テントクルエル",
  klawf: "ガケガニ",
  capsakid: "カプサイジ", scovillain: "スコヴィラン",
  rellor: "コロコロルー", rabsca: "サバンナ",
  flittle: "ヒメヤンマ", espathra: "クエスパトラ",
  tinkatink: "カヌチャン", tinkatuff: "カナツチャン", tinkaton: "デカヌチャン",
  wiglett: "ウミディグダ", wugtrio: "ウミトリオ",
  bombirdier: "オトシドリ",
  finizen: "ナミイルカ", palafin: "イルカマン",
  varoom: "エンジン", revavroom: "レガルエッカ",
  cyclizar: "モトトカゲ",
  orthworm: "ミミズズ",
  glimmet: "タギングル", glimmora: "キラフロル",
  greavard: "ガラルユキカブリ", houndstone: "ハカドッグ",
  flamigo: "クエスパトラ",
  cetoddle: "オタクジラ", cetitan: "ハルクジラ",
  veluza: "ミガルーサ", dondozo: "ヘイラッシャ",
  tatsugiri: "タツギリ",
  annihilape: "コノヨザル",
  clodsire: "ドオー",
  farigiraf: "リキキリン",
  dudunsparce: "ノココッチ",
  kingambit: "ドドゲザン",
  "great-tusk": "イダイナキバ",
  "scream-tail": "サケブシッポ",
  "brute-bonnet": "アラブルタケ",
  "flutter-mane": "ハバタクカミ",
  "slither-wing": "チヲハウハネ",
  "sandy-shocks": "スナノケガワ",
  "iron-treads": "テツノワダチ",
  "iron-bundle": "テツノツツミ",
  "iron-hands": "テツノカイナ",
  "iron-jugulis": "テツノコウベ",
  "iron-moth": "テツノドクガ",
  "iron-thorns": "テツノイバラ",
  frigibax: "セゴール", arctibax: "セゴルゴン", baxcalibur: "セグレイブ",
  gimmighoul: "コレクレー", gholdengo: "サーフゴー",
  "wo-chien": "チヲハウハネ",
  "chien-pao": "パオジアン",
  "ting-lu": "ディンルー",
  "chi-yu": "イーユイ",
  "roaring-moon": "トドロクツキ",
  "iron-valiant": "テツノブシン",
  koraidon: "コライドン", miraidon: "ミライドン",
  "walking-wake": "ウネルミナモ",
  "iron-leaves": "テツノイサハ",
  dipplin: "カミッチュ",
  poltchageist: "チャデス", sinistcha: "ヤバソチャ",
  okidogi: "イイネイヌ", munkidori: "マシマシラ",
  fezandipiti: "キチキギス", ogerpon: "オーガポン",
  "ogerpon-wellspring": "オーガポン(水)",
  "ogerpon-hearthflame": "オーガポン(炎)",
  "ogerpon-cornerstone": "オーガポン(岩)",
  archaludon: "ブリジュラス",
  hydrapple: "カミツオロチ",
  "gouging-fire": "ウガツホムラ",
  "raging-bolt": "タケルライコ",
  "iron-boulder": "テツノイワオ",
  "iron-crown": "テツノカシラ",
  terapagos: "テラパゴス",
  pecharunt: "モモワロウ",

  // マスターデータ用フォルム
  "calyrex-ice": "バドレックス(はくばじょう)",
  "calyrex-shadow": "バドレックス(こくばじょう)",
  "giratina-origin": "ギラティナ(オリジン)",
  "goodra-hisui": "ヌメルゴン(ヒスイ)",
  "kyurem-black": "ブラックキュレム",
  "landorus-therian": "ランドロス(れいじゅう)",
  "muk-alola": "ベトベトン(アローラ)",
  "necrozma-dusk-mane": "ネクロズマ(たそがれ)",
  "ninetales-alola": "アローラキュウコン",
  "arcanine-hisui": "ヒスイウインディ",
  "typhlosion-hisui": "ヒスイバクフーン",
  "samurott-hisui": "ヒスイダイケンキ",
  "avalugg-hisui": "ヒスイクレベース",
  "tauros-paldea-aqua": "パルデアケンタロス(水)",
  "tauros-paldea-blaze": "パルデアケンタロス(炎)",
  "ursaluna-bloodmoon": "ガチグマ(あかつき)",
  "urshifu-rapid-strike": "ウーラオス(れんげき)",
  "urshifu-single-strike": "ウーラオス(いちげき)",
  "weezing-galar": "マタドガス(ガラル)",
  "zacian-crowned": "ザシアン(けんのおう)",
  "zamazenta-crowned": "ザマゼンタ(たてのおう)",
  "zoroark-hisui": "ゾロアーク(ヒスイ)",
};

/** 日本語名 → 英語slug の逆引き */
export const JA_TO_EN: Record<string, string> = Object.fromEntries(
  Object.entries(EN_TO_JA).map(([en, ja]) => [ja, en])
);

/** 英語slug から日本語名を取得（なければslugをそのまま返す） */
export function getJaName(slug: string): string {
  return EN_TO_JA[slug] ?? slug;
}

// フォーム名の漢字→ひらがな変換テーブル
const FORM_ALIAS: Record<string, string> = {
  "霊獣": "れいじゅう", "化身": "けしん", "暁月": "あかつき", "赫月": "あかつき",
  "黒馬": "くろうま", "白馬": "しろうま",
  "剣の王": "けんのおう", "盾の王": "たてのおう",
  "連撃": "れんげき", "一撃": "いちげき",
  "オリジン": "オリジン", "アナザー": "アナザー",
};

const POKEMON_ALIAS: Record<string, string> = {
  "黒バド": "バドレックス(こくばじょう)",
  "黒バドレックス": "バドレックス(こくばじょう)",
  "黒馬バドレックス": "バドレックス(こくばじょう)",
  "白バド": "バドレックス(はくばじょう)",
  "白バドレックス": "バドレックス(はくばじょう)",
  "白馬バドレックス": "バドレックス(はくばじょう)",
  "連撃ウーラオス": "ウーラオス(れんげき)",
  "一撃ウーラオス": "ウーラオス(いちげき)",
  "水オーガポン": "オーガポン(水)",
  "炎オーガポン": "オーガポン(炎)",
  "岩オーガポン": "オーガポン(岩)",
};

function normalizePokemonAlias(jaName: string): string {
  let normalized = jaName.trim().replace(/（/g, "(").replace(/）/g, ")");
  normalized = POKEMON_ALIAS[normalized] ?? normalized;
  for (const [kanji, hira] of Object.entries(FORM_ALIAS)) {
    normalized = normalized.replace(kanji, hira);
  }
  return POKEMON_ALIAS[normalized] ?? normalized;
}

export function resolvePokemonJaName(input: string): string | null {
  const cleaned = normalizePokemonAlias(
    input
      .replace(/^[■□◆◇●○・•◦▪︎▸▶︎>]+/, "")
      .replace(/^(ポケモン|名前)[:：]/, "")
      .trim()
  ).replace(/\s/g, "");

  if (!cleaned) return null;
  if (JA_TO_EN[cleaned]) return EN_TO_JA[JA_TO_EN[cleaned]] ?? cleaned;

  const normalized = normalizeJaText(cleaned);
  if (normalized.length < 3) return null;

  const candidates = Object.values(EN_TO_JA);
  const exact = candidates.find((candidate) => normalizeJaText(candidate) === normalized);
  if (exact) return exact;

  return findBestJaMatch(cleaned, candidates, {
    maxDistance: normalized.length >= 6 ? 3 : 2,
  });
}

/** 日本語名から英語slugを取得（完全一致→フォーム名正規化→部分一致） */
export function getEnSlug(jaName: string): string | null {
  const aliasNormalized = normalizePokemonAlias(jaName);

  // 1. 完全一致
  if (JA_TO_EN[jaName]) return JA_TO_EN[jaName];
  if (JA_TO_EN[aliasNormalized]) return JA_TO_EN[aliasNormalized];

  // 2. フォーム名の漢字→ひらがな変換して再検索
  let normalized = aliasNormalized;
  if (JA_TO_EN[normalized]) return JA_TO_EN[normalized];

  // 3. 「霊獣ランドロス」→「ランドロス(れいじゅう)」形式に変換
  for (const [kanji, hira] of Object.entries(FORM_ALIAS)) {
    if (aliasNormalized.startsWith(kanji)) {
      const baseName = aliasNormalized.slice(kanji.length);
      const withForm = `${baseName}(${hira})`;
      if (JA_TO_EN[withForm]) return JA_TO_EN[withForm];
    }
  }

  // 4. 部分一致（「ランドロス」で「landorus」を見つける）
  for (const [ja, en] of Object.entries(JA_TO_EN)) {
    if (ja === aliasNormalized || ja.startsWith(aliasNormalized)) return en;
  }

  return null;
}

/** 日本語名からフォーム違いを含む候補一覧を取得 */
export function findPokemonCandidates(jaName: string): Array<{ name: string; ja: string }> {
  // フォーム名変換
  const searchName = normalizePokemonAlias(jaName);

  // ベース名を抽出（括弧やフォーム名を除去）
  const baseName = searchName.replace(/\(.*?\)/, "").replace(/^(れいじゅう|けしん|あかつき|くろうま|しろうま|れんげき|いちげき)/, "");

  const candidates: Array<{ name: string; ja: string }> = [];
  for (const [en, ja] of Object.entries(EN_TO_JA)) {
    if (ja === searchName || ja.startsWith(baseName)) {
      candidates.push({ name: en, ja });
    }
  }
  return candidates;
}

/** 日本語名でポケモン検索（前方一致・部分一致） */
export function searchByJaName(query: string, limit = 8): Array<{ name: string; ja: string }> {
  const results: Array<{ name: string; ja: string }> = [];
  const q = query.trim();
  if (!q) return results;

  // 前方一致を優先
  const prefix: Array<{ name: string; ja: string }> = [];
  const contains: Array<{ name: string; ja: string }> = [];

  for (const [en, ja] of Object.entries(EN_TO_JA)) {
    if (ja.startsWith(q)) prefix.push({ name: en, ja });
    else if (ja.includes(q)) contains.push({ name: en, ja });
  }

  return [...prefix, ...contains].slice(0, limit);
}
